name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        REPOSITORY: backend-github-action 
      run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: sudo docker build -t $DOCKER_USERNAME/$REPOSITORY:stable -t $DOCKER_USERNAME/$REPOSITORY:dev  .
    - name: Pushing to Dockerhub
      run: |
        sudo docker push $DOCKER_USERNAME/$REPOSITORY:stable
        sudo docker push $DOCKER_USERNAME/$REPOSITORY:dev
