name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}} 
      run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: sudo docker build -t subash729/backend-github-action:stable -t subash729/backend-github-action:dev  .
    - name: Pushing to Dockerhub
      run: |
        sudo docker push subash729/backend-github-action:stable
        sudo docker push subash729/backend-github-action:dev
