name: Frontend Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: sudo docker build -t subash729/frontend-github-action:dev -t subash729/frontend-github-action:$(git rev-parse HEAD) -f Dockerfile.frontend .

  push:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}} 
      run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Pushing to Dockerhub
      run: |
        sudo docker push subash729/frontend-github-action:dev
        sudo docker push subash729/frontend-github-action:$(git rev-parse HEAD)      
  increase-version:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set Git user identity
      run: |
        git config --global user.email "subaschy729@gmail.com"
        git config --global user.name "Subash Chaudhary"

    - name: Increase version in package.json
      run: |
        yarn version --patch
#        git push --follow-tag

